# Generated by Django 4.1 on 2022-08-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=150, verbose_name='email address')),
                ('id_number', models.BigIntegerField(max_length=13, verbose_name='id number')),
                ('phone_number', models.BigIntegerField(max_length=10, verbose_name='cellphone number')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
            ],
        ),
    ]
