# Generated by Django 4.1 on 2022-08-27 18:52

import BackOfficeApp.utils.product.product
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Loan Amount')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate')),
                ('created_at', models.DateTimeField(verbose_name='Created Date')),
                ('number_of_products', models.IntegerField(verbose_name='Number Of Products')),
                ('payment_due_date', models.DateField(verbose_name='Payment Due Date')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email Address')),
                ('id_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[0-9]+$'), django.core.validators.MinLengthValidator(13)], verbose_name='ID Number')),
                ('cell_phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$'), django.core.validators.MinLengthValidator(10)], verbose_name='Cellphone Number')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('home_address', models.TextField(default='', max_length=255, verbose_name='Home Address')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='KeepProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep_image', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('serial_number', models.CharField(max_length=150, verbose_name='Serial Number')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Market Value')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='Account Id')),
                ('hash_value', models.CharField(max_length=255, verbose_name='Request Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=BackOfficeApp.utils.product.product.content_file_name)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.customer')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('SOLD', 'SOLD'), ('REMOVED', 'REMOVED'), ('UNAVAILABLE', 'UNAVAILABLE')], default='AVAILABLE', max_length=255)),
                ('created_at', models.DateTimeField(verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(verbose_name='Updated Date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.account')),
                ('product_item', models.ManyToManyField(to='BackOfficeApp.productitem')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.customer'),
        ),
    ]
