# Generated by Django 4.1 on 2022-08-18 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0002_alter_customer_id_number_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='home_address',
            field=models.CharField(default='', max_length=255, verbose_name='home address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(13)], verbose_name='id number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)], verbose_name='phone number'),
        ),
    ]
