# Generated by Django 4.1 on 2022-08-18 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0007_alter_customer_id_number_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='home_address',
            field=models.TextField(default='', max_length=255, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[0-9]+$'), django.core.validators.MinLengthValidator(13)], verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$'), django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number'),
        ),
    ]
