# Generated by Django 4.1 on 2022-08-19 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0008_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='cell_phone_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$'), django.core.validators.MinLengthValidator(10)], verbose_name='Cellphone Number'),
            preserve_default=False,
        ),
    ]
