# Generated by Django 4.1 on 2022-08-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0010_account_productitem_customerasset_catalogue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='productitem',
            name='description',
            field=models.TextField(default='', max_length=255, verbose_name='Description'),
        ),
    ]
