# Generated by Django 4.1 on 2022-08-19 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0011_productcategory_productitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.productcategory'),
        ),
    ]
