# Generated by Django 4.1 on 2022-08-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0012_alter_productitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
