# Generated by Django 4.1 on 2022-08-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0013_alter_productitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountitem',
            name='account_number',
        ),
    ]
