# Generated by Django 4.1 on 2022-08-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0014_remove_accountitem_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='account',
            name='loan_amount',
            field=models.BigIntegerField(verbose_name='Loan Amount'),
        ),
    ]
