# Generated by Django 4.1 on 2022-08-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0016_remove_account_customer_account_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.customer'),
            preserve_default=False,
        ),
    ]
