# Generated by Django 4.1 on 2022-08-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0017_account_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Loan Amount'),
        ),
    ]
