# Generated by Django 4.1 on 2022-08-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0018_alter_account_loan_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='sale_date',
        ),
        migrations.AlterField(
            model_name='account',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Loan Amount'),
        ),
    ]
