# Generated by Django 4.1 on 2022-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0019_remove_account_sale_date_alter_account_loan_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='account',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Rate'),
        ),
    ]
