# Generated by Django 4.1 on 2022-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0020_alter_account_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate'),
        ),
    ]
