# Generated by Django 4.1 on 2022-08-22 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0021_alter_account_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Market Value'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated Date'),
        ),
    ]
