# Generated by Django 4.1 on 2022-08-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0022_accountitem_created_at_alter_account_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackOfficeApp.productitem')),
            ],
        ),
    ]
