# Generated by Django 4.1 on 2022-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0024_alter_productitemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number_of_products',
            field=models.IntegerField(default=1, verbose_name='Number Of Products'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='operative_date',
            field=models.DateField(verbose_name='Payment Due Date'),
        ),
    ]
