# Generated by Django 4.1 on 2022-08-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOfficeApp', '0025_account_number_of_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='Account Id')),
                ('hash_value', models.CharField(max_length=255, verbose_name='Request Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_products',
            field=models.IntegerField(verbose_name='Number Of Products'),
        ),
    ]
