# Generated by Django 4.1 on 2022-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionApp', '0003_paymentrequestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResponseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=32)),
                ('data', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentrequestdata',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
